"""Initial schema with all recipe fields

Revision ID: 7e7d00307566
Revises: 
Create Date: 2025-11-26 21:31:50.110636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7d00307566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
